openapi: 3.0.0
info:
  title: Linkedin Developer APIs
  version: 1.0.0
  description: ''
servers:
  - url: 'http://localhost:4000'
    description: Local
  - url: 'https://www.linkedin.com'
    description: prod
paths:
  /api/authToken:
    post:
      summary: Exchange Authorization Code for an Access Token
      tags:
        - Authorization API
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              additionalProperties: false
              required:
                - grant_type
                - code
                - client_id
                - client_secret
                - redirect_uri
              properties:
                grant_type:
                  type: string
                  description: The value of this field should always be:authorization_code
                  enum:
                    - authorization_code
                code:
                  type: string
                  description: The authorization code you received in Step 2.
                client_id:
                  type: string
                  description: The Client ID value generated in Step 1.
                client_secret:
                  type: string
                  description: The Secret Key value generated in Step 1.
                redirect_uri:
                  type: string
                  description: The same redirect_uri value that you passed in the previous step.
      responses:
        '200':
          description: Get Access Token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: 'string'
                    example: 'AQXNnd2kXITHELmWblJigbHEuoFdfRhOwGQNnu...'
                  expires_in:
                    type: number
                    example: 5184000
        '401':
          description: Unauthorized Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
              example:
                error: invalid_request,
                error_description: Unable to retrieve access token :authorization code not found
        '400':
          description: NOT found required parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
              example:
                - error: invalid_request,
                  error_description: A required parameter "client_secret" is missing
                - error: invalid_request,
                  error_description: A required parameter "client_id" is missing
                - error: invalid_request,
                  error_description: A required parameter "grant_type" is missing
                - error: invalid_request,
                  error_description: A required parameter "code" is missing
                - error: invalid_redirect_uri,
                  error_description: Unable to retrieve access token :appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists
                - error: invalid_redirect_uri,
                  error_description: A required parameter "client_secret" is missing
  /api/userProfile:
    get:
      summary: Get User Linkedin Profile
      tags:
        - User API
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Get Member's Profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstName:
                    type: object
                    properties:
                      localized:
                        type: object
                        properties:
                          en-US:
                            type: string
                      preferredLocale:
                        type: object
                        properties:
                          country:
                            type: string
                          language:
                            type: string
                  lastName:
                    type: object
                    properties:
                      localized:
                        type: object
                        properties:
                          en-US:
                            type: string
                      preferredLocale:
                        type: object
                        properties:
                          country:
                            type: string
                          language:
                            type: string
                  profilePicture:
                    type: object
                    properties:
                      displayImage:
                        type: string
                      displayImage~:
                        type: object
                        properties:
                          paging:
                            type: object
                            properties:
                              count:
                                type: number
                              start:
                                type: number
                              links:
                                type: array
                                items:
                                  type: string
                          elements:
                            type: array
                            items:
                              type: object
                              properties:
                                artifact:
                                  type: string
                                authorizationMethod:
                                  type: string
                                data:
                                  type: object
                                  properties:
                                    com.linkedin.digitalmedia.mediaartifact.StillImage:
                                      type: object
                                      properties:
                                        mediaType:
                                          type: string
                                        rawCodecSpec:
                                          type: object
                                          properties:
                                            name:
                                              type: string
                                            type:
                                              type: string
                                        displaySize:
                                          type: object
                                          properties:
                                            width:
                                              type: number
                                            uom:
                                              type: string
                                            height:
                                              type: integer
                                        storageSize:
                                          type: object
                                          properties:
                                            width:
                                              type: number
                                            height:
                                              type: number
                                        storageAspectRatio:
                                          type: object
                                          properties:
                                            widthAspect:
                                              type: number
                                            heightAspect:
                                              type: number
                                            formatted:
                                              type: string
                                        dislayAspectRatio:
                                          type: object
                                          properties:
                                            widthAspect:
                                              type: number
                                            heightAspect:
                                              type: number
                                            formatted:
                                              type: string
                                identifiers:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      identifier:
                                        type: string
                                      index:
                                        type: number
                                      mediaType:
                                        type: string
                                      file:
                                        type: string
                                      identifierType:
                                        type: string
                                      identifierExpiresInSeconds:
                                        type: number
                  id:
                    type: string
                  elements:
                    type: array
                    items:
                      type: object
                      properties:
                        handle~:
                          type: object
                          properties:
                            emailAddress:
                              type: string
                        handle:
                          type: string
        '401':
          description: Unauthorized Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
              example:
                error: invalid_request,
                error_description: Unable to retrieve access token :authorization code not found
  /api/createPost:
    post:
      summary: Create Post with text or Article or Image.
      tags:
        - Linkedin Posts API
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/multipart/form-data:
            schema:
              type: object
              additionalProperties: false
              required:
                - text
                - authorId
                - shareMediaCategory
              properties:
                authorId:
                  type: string
                  example: "KCJAPTnAHO"
                shareMediaCategory:
                  type: string
                  enum: ["IMAGE", "ARTICLE", "TEXT"]
                  example: "IMAGE"
                text:
                  type: string
                  example: "This is a first Post"
                mediaTitle:
                  type: string
                  example: "This is an Media Title"
                mediaDescription:
                  type: string
                  example: "This is an alt attribute"
                image:
                  type: string
                  format: base64
            encoding: # The same level as schema
              image: # Property name (see above)
                contentType: image/png, image/jpeg
      responses:
        "200":
          description: "Get urn link of the created Post"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "urn:li:share:7000694782377267200"
        "415":
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
              example: 
                message: "Extension is not valid. Please upload with .png, .jpeg, .gif files only."
        '401':
          description: Unauthorized Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
              example:
                error: invalid_request,
                error_description: Unable to retrieve access token :authorization code not found
components:
  schemas:
    '401':
      title: '401 Unauthorized Request'
      type: object
      description: Unauthorized Request
      properties:
        error:
          type: string
          description: Error Code for request
        error_description:
          type: string
          description: Error message
    '400':
      title: '400 Invalid Parameters'
      type: object
      description: Missing a required paramter
      properties:
        error:
          type: string
          description: Error code for request
        error_description:
          type: string
          description: Error message
    '415':
      title: '415 Unsupported Media Type'
      type: object
      description: Invalid media type
      properties:
        message:
          type: string
          description: Error message for unsupported file
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
